name: Notify success
description: Sends a notification that a workflow has finished
inputs:
  DESTINATION_URL:
    description: 'Webhook notification URL'
    type: string
  WORKFLOW_NAME:
    description: 'Workflow name'
    required: true
    type: string
  BOT_USERNAME:
    description: 'Username to use for the discord bot message'
    default: 'CC BuildBot'
    required: false
    type: string
  BOT_AVATAR:
    description: 'URL to use for the avatar of the discord bot message'
    default: 'https://static.classicube.net/img/cc-cube-small.png'
    required: false
    type: string
  NOTIFY_MESSAGE:
    description: 'Notification message to send'
    default: 'Successfully compiled MCGalaxy build'
    required: false
    type: string

runs:
  using: "composite"
  steps:
    - name: Notify success
      shell: sh
      if: ${{ inputs.DESTINATION_URL != '' }}
      run: |
        curl ${{ inputs.NOTIFY_URL }} -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"username\": \"${{ inputs.BOT_USERNAME }}\", \"avatar_url\": \"${{ inputs.BOT_AVATAR }}\", \"content\": \"${{ inputs.NOTIFY_MESSAGE }}\" }"